{
 "title": "Azure / AI",
 "description": "The dashboard provides insights of Azure Apps via different metrics for app monitoring through Application Insights.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "sub", "label": "Subscription", "query": "Subscriptions()" },
   { "name": "rg", "label": "Resource Group", "query": "ResourceGroups($sub)" },
   { "name": "ns", "label": "Namespace", "query": "Namespaces($sub, $rg)" },
   { "name": "res", "label": "Resource", "query": "ResourceNames($sub, $rg, $ns)" },
   {
    "name": "tenant",
    "label": "tenantId",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Number of requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "requests\n| where timestamp >= $__timeFrom and timestamp < $__timeTo\n| where customDimensions['http.method'] != 'OPTIONS'\n| count \n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "requests\n| where timestamp >= $__timeFrom and timestamp < $__timeTo\n| summarize AvgResponseTime = avg(duration) \n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Total tokens used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "dependencies\n| where $__timeFilter(timestamp)\n| extend model = tostring(customDimensions[\"gen_ai.response.model\"])\n| where model != \"\"\n| extend\n    prompt_tokens = toint(customDimensions[\"gen_ai.usage.input_tokens\"]),\n    completion_tokens = toint(customDimensions[\"gen_ai.usage.output_tokens\"])\n| summarize total = sum(prompt_tokens +completion_tokens)",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Server Response Time (sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 3 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let minDuration = iif(isempty(\"$min_duration\"), \"0\", \"$min_duration\");\nlet maxDuration = iif(isempty(\"$max_duration\"), \"0\", \"$max_duration\");\n\nrequests// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n//| where (\"All\" in ($operation_name) or operation_Name in ($operation_name))\n//| where duration >= todouble(minDuration) and duration <= todouble(maxDuration)\n// calculate average request duration for all requests\n| summarize AVG = avg(duration), P95 = percentiles(duration, 95), MAX = max(duration) by bin(timestamp, $__interval)\n| project timestamp, AVG = AVG/1000, P95 = P95/1000, MAX = MAX/1000\n| order by timestamp asc\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Count of Requests by Server Response Time (sec)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 11, "x": 10, "y": 3 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "requests\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n// calculate average request duration for all requests\n| extend ResponseTime = duration/1000\n| project timestamp, ResponseTime\n| order by timestamp asc\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Tokens Used by Model",
   "type": "table",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 13 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "dependencies\r\n| where $__timeFilter(timestamp)\r\n| extend model = tostring(customDimensions[\"gen_ai.response.model\"])\r\n| where model != \"\"\r\n| extend\r\n    deployment = tostring(customDimensions[\"gen_ai.request.model\"]),\r\n    prompt_tokens = toint(customDimensions[\"gen_ai.usage.input_tokens\"]),\r\n    completion_tokens = toint(customDimensions[\"gen_ai.usage.output_tokens\"])\r\n| summarize prompt = sum(prompt_tokens), completion = sum(completion_tokens), total = sum(prompt_tokens +completion_tokens) by model, deployment",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/Microsoft.Insights/components/$res"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": " Average Model Duration (Sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "dependencies\r\n| where $__timeFilter(timestamp)\r\n| extend model = tostring(customDimensions[\"gen_ai.response.model\"])\r\n| where model != \"\"\r\n| project timestamp, duration_sec=duration/1000, model\r\n| summarize duration_sec = avg(duration_sec) by bin(timestamp, 1m), model\r\n| evaluate pivot(model, avg(duration_sec))\r\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/Microsoft.Insights/components/$res"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Tokens Used Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 20 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "dependencies\r\n| where $__timeFilter(timestamp)\r\n| extend\r\n    prompt_tokens = toint(customDimensions[\"gen_ai.usage.input_tokens\"]),\r\n    completion_tokens = toint(customDimensions[\"gen_ai.usage.output_tokens\"])\r\n| summarize sum_total_tokens=sum(prompt_tokens+completion_tokens), sum(prompt_tokens), sum(completion_tokens) by bin(timestamp, 5m) ",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/Microsoft.Insights/components/$res"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Top 20 Operations by Relevance",
   "type": "table",
   "description": "Click on the OperationID or Name to open the trace details in explore mode.",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 30 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let minDuration = iif(isempty(\"$min_duration\"), \"0\", \"$min_duration\");\nlet maxDuration = iif(isempty(\"$max_duration\"), \"0\", \"$max_duration\");\n\nlet min_length_8 = (s: string) {\n    let len = strlen(s);\n    case(len == 1, strcat(s, s, s, s, s, s, s, s),\n        len == 2 or len == 3, strcat(s, s, s, s),\n        len == 4 or len == 5 or len == 6 or len == 7, strcat(s, s),\n        s)\n};\nlet ai_hash = (s: string) {\n    abs(toint(__hash_djb2(min_length_8(s))))\n};\nrequests\n//| where (\"All\" in ($operation_name) or operation_Name in ($operation_name))\n| where $__timeFilter(timestamp)\n| where customDimensions['http.method'] != 'OPTIONS'\n//| where duration >= todouble(minDuration) and duration <= todouble(maxDuration)\n| project Name = operation_Name, Time=timestamp, ResponseCode = resultCode, ResponseTime = duration, OperationID = operation_Id, Score=ai_hash(operation_Id)\n| top 20 by Score asc",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}